# Usar una imagen base de Nginx (para un sitio web estático)
FROM nginx:alpine

# Copiar el contenido del sitio web a la carpeta de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

