version: '3.8'

services:
  web:
    build:
      context: ./sitio
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

